### ISSUE TITLE
Upload Error (upload dont works on files bigger than 499mb)

### ISSUE THREAD

**Issue by javiermzelaya** [jamesheck2019/MediaFire-Explorer#2]
Hello file upload dont works on files bigger than 499mb,  can you fix this please? Thank u

https://i.imgur.com/gHQMOcp.jpg

**Comment by jamesheck2019** [comment]
> Hello file upload dont works on files bigger than 499mb, can you fix this please? Thank u
> 
> https://i.imgur.com/gHQMOcp.jpg

immediately throw exception when upload strarts? or after upload finished? or after some times (during uploading)?

**Comment by javiermzelaya** [comment]
I tried with a 500mb file and the upload was correct, the error starts with 501mb files, I try with 1gb and 2gb files with same error, upload never starts error appears after some seconds.

**Comment by jamesheck2019** [comment]
fixed, new release tomorrow
[https://imgur.com/Wu5sU5w](https://imgur.com/Wu5sU5w)

**Comment by jamesheck2019** [comment]
version [2.0.0](https://github.com/jamesheck2019/MediaFire-Explorer/releases/tag/2.0.0.0)
if ok let me know to close the issue
